# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Loop-Prima
version:      1.00
version_from: Prima.pm
installdirs:  site
requires:
    POE:                           0
    Prima:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
